export interface IconDefinition {
    icon: string;
    tags: string[];
}

export const ICON_LIBRARY: IconDefinition[] = [
    // Food & Drink
    { icon: '🍔', tags: ['food', 'burger', 'fast food', 'comida', 'hamburguesa'] },
    { icon: '🍕', tags: ['food', 'pizza', 'italian', 'comida'] },
    { icon: '🥗', tags: ['food', 'salad', 'healthy', 'comida', 'ensalada'] },
    { icon: '🍣', tags: ['food', 'sushi', 'japanese', 'comida'] },
    { icon: '🍜', tags: ['food', 'noodle', 'ramen', 'asian', 'comida'] },
    { icon: '🍝', tags: ['food', 'pasta', 'italian', 'comida'] },
    { icon: '🌮', tags: ['food', 'taco', 'mexican', 'comida'] },
    { icon: '🌯', tags: ['food', 'burrito', 'mexican', 'comida'] },
    { icon: '🥩', tags: ['food', 'meat', 'steak', 'carne'] },
    { icon: '🍗', tags: ['food', 'chicken', 'poultry', 'pollo'] },
    { icon: '🥓', tags: ['food', 'bacon', 'breakfast', 'panceta'] },
    { icon: '🍳', tags: ['food', 'egg', 'breakfast', 'cooking', 'huevo'] },
    { icon: '🥐', tags: ['food', 'croissant', 'bakery', 'breakfast', 'bolleria'] },
    { icon: '🥖', tags: ['food', 'bread', 'bakery', 'pan'] },
    { icon: '🥞', tags: ['food', 'pancake', 'breakfast', 'tortitas'] },
    { icon: '🍟', tags: ['food', 'fries', 'fast food', 'patatas'] },
    { icon: '🌭', tags: ['food', 'hotdog', 'fast food', 'perrito'] },
    { icon: '🥪', tags: ['food', 'sandwich', 'lunch', 'bocadillo'] },
    { icon: '🍦', tags: ['food', 'ice cream', 'dessert', 'helado'] },
    { icon: '🍩', tags: ['food', 'donut', 'dessert', 'rosquilla'] },
    { icon: '🍰', tags: ['food', 'cake', 'dessert', 'pastel'] },
    { icon: '🍪', tags: ['food', 'cookie', 'biscuit', 'galleta'] },
    { icon: '🍫', tags: ['food', 'chocolate', 'candy', 'dulce'] },
    { icon: '🍬', tags: ['food', 'candy', 'sweet', 'caramelo'] },
    { icon: '🍎', tags: ['food', 'fruit', 'apple', 'healthy', 'manzana'] },
    { icon: '🍌', tags: ['food', 'fruit', 'banana', 'healthy', 'platano'] },
    { icon: '🍇', tags: ['food', 'fruit', 'grapes', 'uvas'] },
    { icon: '🍓', tags: ['food', 'fruit', 'strawberry', 'fresa'] },
    { icon: '🍒', tags: ['food', 'fruit', 'cherry', 'cereza'] },
    { icon: '🥑', tags: ['food', 'vegetable', 'avocado', 'healthy', 'aguacate'] },
    { icon: '🥦', tags: ['food', 'vegetable', 'broccoli', 'healthy', 'brocoli'] },
    { icon: '🥕', tags: ['food', 'vegetable', 'carrot', 'healthy', 'zanahoria'] },
    { icon: '☕', tags: ['drink', 'coffee', 'cafe', 'breakfast', 'bebida', 'cafe'] },
    { icon: '🍵', tags: ['drink', 'tea', 'matcha', 'te'] },
    { icon: '🥤', tags: ['drink', 'soda', 'soft drink', 'refresco'] },
    { icon: '🧃', tags: ['drink', 'juice', 'box', 'zumo'] },
    { icon: '🍺', tags: ['drink', 'beer', 'alcohol', 'bar', 'cerveza'] },
    { icon: '🍷', tags: ['drink', 'wine', 'alcohol', 'vino'] },
    { icon: '🍸', tags: ['drink', 'cocktail', 'alcohol', 'party', 'copa'] },
    { icon: '🍹', tags: ['drink', 'cocktail', 'tropical', 'bebida'] },
    { icon: '🛒', tags: ['shopping', 'grocery', 'supermarket', 'compra', 'super'] },
    { icon: '🍽️', tags: ['food', 'restaurant', 'dinner', 'plate', 'restaurante'] },

    // Transport & Travel
    { icon: '🚗', tags: ['transport', 'car', 'gas', 'fuel', 'auto', 'coche', 'gasolina'] },
    { icon: '🚕', tags: ['transport', 'taxi', 'cab', 'uber'] },
    { icon: '🚌', tags: ['transport', 'bus', 'public', 'autobus'] },
    { icon: '🚎', tags: ['transport', 'trolley', 'tram'] },
    { icon: '🏎️', tags: ['transport', 'race', 'car', 'carreras'] },
    { icon: '🚓', tags: ['transport', 'police', 'car', 'policia'] },
    { icon: '🚑', tags: ['transport', 'ambulance', 'medical', 'ambulancia'] },
    { icon: '🚒', tags: ['transport', 'fire', 'truck', 'bomberos'] },
    { icon: '🚚', tags: ['transport', 'truck', 'delivery', 'camion'] },
    { icon: '🚜', tags: ['transport', 'tractor', 'farm'] },
    { icon: '🏍️', tags: ['transport', 'motorcycle', 'bike', 'moto'] },
    { icon: '🛵', tags: ['transport', 'scooter', 'delivery', 'ciclomotor'] },
    { icon: '🚲', tags: ['transport', 'bike', 'cycling', 'sport', 'bici'] },
    { icon: '🛴', tags: ['transport', 'scooter', 'kick', 'patinete'] },
    { icon: '🚇', tags: ['transport', 'train', 'subway', 'metro'] },
    { icon: '🚆', tags: ['transport', 'train', 'rail', 'tren'] },
    { icon: '✈️', tags: ['transport', 'travel', 'flight', 'trip', 'viaje', 'avion'] },
    { icon: '🚀', tags: ['transport', 'rocket', 'space'] },
    { icon: '🚁', tags: ['transport', 'helicopter', 'fly', 'helicoptero'] },
    { icon: '🚢', tags: ['transport', 'ship', 'boat', 'cruise', 'barco'] },
    { icon: '⛽', tags: ['transport', 'fuel', 'gas', 'station', 'gasolinera'] },
    { icon: '🔧', tags: ['transport', 'repair', 'mechanic', 'taller'] },
    { icon: '🅿️', tags: ['transport', 'parking', 'garage', 'aparcamiento'] },
    { icon: '🗺️', tags: ['travel', 'map', 'tourist', 'mapa'] },
    { icon: '🌍', tags: ['travel', 'world', 'earth', 'global'] },
    { icon: '🏖️', tags: ['travel', 'beach', 'summer', 'vacation', 'playa'] },
    { icon: '🏔️', tags: ['travel', 'mountain', 'nature', 'hiking', 'montana'] },
    { icon: '🏕️', tags: ['travel', 'camping', 'nature', 'tent'] },
    { icon: '🏨', tags: ['travel', 'hotel', 'accommodation', 'lodging'] },

    // Home & Utilities
    { icon: '🏠', tags: ['home', 'rent', 'mortgage', 'house', 'casa', 'alquiler'] },
    { icon: '🏡', tags: ['home', 'house', 'garden', 'jardin'] },
    { icon: '🏢', tags: ['home', 'building', 'office', 'edificio'] },
    { icon: '💡', tags: ['bill', 'electricity', 'light', 'utility', 'luz', 'factura'] },
    { icon: '💧', tags: ['bill', 'water', 'utility', 'agua'] },
    { icon: '🔥', tags: ['bill', 'gas', 'heating', 'heat', 'fuego'] },
    { icon: '📶', tags: ['bill', 'internet', 'wifi', 'phone', 'wifi'] },
    { icon: '📱', tags: ['bill', 'phone', 'mobile', 'celular', 'movil'] },
    { icon: '☎️', tags: ['bill', 'phone', 'landline', 'fijo'] },
    { icon: '📺', tags: ['home', 'tv', 'television', 'entertainment', 'television'] },
    { icon: '🛋️', tags: ['home', 'furniture', 'decoration', 'living', 'mueble'] },
    { icon: '🛏️', tags: ['home', 'bed', 'sleep', 'bedroom', 'cama'] },
    { icon: '🚪', tags: ['home', 'door', 'room', 'puerta'] },
    { icon: '🚽', tags: ['home', 'toilet', 'bathroom', 'bano'] },
    { icon: '🚿', tags: ['home', 'shower', 'water', 'ducha'] },
    { icon: '🧹', tags: ['home', 'cleaning', 'broom', 'limpieza'] },
    { icon: '🧺', tags: ['home', 'laundry', 'clothes', 'lavanderia'] },
    { icon: '🛠️', tags: ['home', 'repair', 'tools', 'diy', 'reparacion'] },
    { icon: '🔨', tags: ['home', 'hammer', 'construction', 'martillo'] },
    { icon: '🗑️', tags: ['home', 'trash', 'waste', 'basura'] },
    { icon: '📦', tags: ['home', 'box', 'package', 'shipping', 'paquete'] },

    // Shopping & Personal
    { icon: '🛍️', tags: ['shopping', 'clothes', 'fashion', 'mall', 'ropa', 'compras'] },
    { icon: '👕', tags: ['shopping', 'shirt', 'clothes', 'tshirt', 'camiseta'] },
    { icon: '👖', tags: ['shopping', 'jeans', 'pants', 'clothes', 'pantalones'] },
    { icon: '👗', tags: ['shopping', 'dress', 'clothes', 'fashion', 'vestido'] },
    { icon: '🧥', tags: ['shopping', 'coat', 'jacket', 'winter', 'abrigo'] },
    { icon: '👞', tags: ['shopping', 'shoe', 'formal', 'zapatos'] },
    { icon: '👟', tags: ['shopping', 'shoes', 'sneakers', 'sport', 'zapatillas'] },
    { icon: '👠', tags: ['shopping', 'heels', 'shoes', 'fashion', 'tacones'] },
    { icon: '👢', tags: ['shopping', 'boots', 'shoes', 'botas'] },
    { icon: '👒', tags: ['shopping', 'hat', 'cap', 'gorro'] },
    { icon: '🎒', tags: ['shopping', 'backpack', 'school', 'travel', 'mochila'] },
    { icon: '👜', tags: ['shopping', 'bag', 'purse', 'fashion', 'bolso'] },
    { icon: '💍', tags: ['shopping', 'jewelry', 'ring', 'wedding', 'joya', 'anillo'] },
    { icon: '💄', tags: ['personal', 'makeup', 'beauty', 'cosmetics', 'maquillaje'] },
    { icon: '🧴', tags: ['personal', 'lotion', 'cream', 'beauty', 'crema'] },
    { icon: '👓', tags: ['personal', 'glasses', 'vision', 'gafas'] },
    { icon: '🕶️', tags: ['personal', 'sunglasses', 'summer', 'gafas sol'] },
    { icon: '💇', tags: ['personal', 'hair', 'beauty', 'salon', 'barber', 'pelo'] },
    { icon: '💅', tags: ['personal', 'nails', 'manicure', 'spa', 'unas'] },
    { icon: '🧖', tags: ['personal', 'spa', 'sauna', 'relax'] },
    { icon: '🛀', tags: ['personal', 'bath', 'relax', 'bano'] },

    // Health
    { icon: '💊', tags: ['health', 'medicine', 'drug', 'pharmacy', 'salud', 'farmacia'] },
    { icon: '💉', tags: ['health', 'syringe', 'vaccine', 'doctor', 'vacuna'] },
    { icon: '🏥', tags: ['health', 'hospital', 'clinic', 'emergency', 'hospital'] },
    { icon: '🚑', tags: ['health', 'ambulance', 'emergency', 'ambulancia'] },
    { icon: '🩺', tags: ['health', 'stethoscope', 'doctor', 'checkup', 'medico'] },
    { icon: '🩹', tags: ['health', 'bandage', 'aid', 'hurt', 'tirita'] },
    { icon: '🦷', tags: ['health', 'dentist', 'teeth', 'tooth', 'dentista'] },
    { icon: '🩸', tags: ['health', 'blood', 'donation', 'test', 'sangre'] },
    { icon: '🌡️', tags: ['health', 'thermometer', 'sick', 'fever', 'fiebre'] },
    { icon: '🏋️', tags: ['health', 'gym', 'fitness', 'workout', 'gimnasio'] },
    { icon: '🧘', tags: ['health', 'yoga', 'meditation', 'wellness'] },
    { icon: '🏊', tags: ['health', 'swim', 'pool', 'sport', 'natacion'] },
    { icon: '🏃', tags: ['health', 'run', 'jog', 'sport', 'correr'] },
    { icon: '🤸', tags: ['health', 'gymnastics', 'activity', 'sport'] },

    // Entertainment & Hobbies
    { icon: '🎮', tags: ['fun', 'game', 'console', 'playstation', 'xbox', 'juego'] },
    { icon: '🕹️', tags: ['fun', 'joystick', 'arcade', 'retro'] },
    { icon: '🎲', tags: ['fun', 'dice', 'board game', 'casino'] },
    { icon: '🎬', tags: ['fun', 'movie', 'cinema', 'film', 'theater', 'cine'] },
    { icon: '🍿', tags: ['fun', 'popcorn', 'movie', 'snack', 'palomitas'] },
    { icon: '🎟️', tags: ['fun', 'ticket', 'cinema', 'show', 'entrada'] },
    { icon: '🎵', tags: ['fun', 'music', 'note', 'song', 'musica'] },
    { icon: '🎧', tags: ['fun', 'headphones', 'music', 'audio', 'auriculares'] },
    { icon: '🎤', tags: ['fun', 'microphone', 'karaoke', 'sing', 'microfono'] },
    { icon: '🎹', tags: ['fun', 'piano', 'instrument', 'music'] },
    { icon: '🎸', tags: ['fun', 'guitar', 'instrument', 'music', 'guitarra'] },
    { icon: '🥁', tags: ['fun', 'drum', 'instrument', 'music', 'bateria'] },
    { icon: '🎺', tags: ['fun', 'trumpet', 'instrument', 'music', 'trompeta'] },
    { icon: '🎻', tags: ['fun', 'violin', 'instrument', 'music', 'violin'] },
    { icon: '⚽', tags: ['fun', 'soccer', 'football', 'sport', 'futbol'] },
    { icon: '🏀', tags: ['fun', 'basketball', 'sport', 'baloncesto'] },
    { icon: '🏈', tags: ['fun', 'football', 'american', 'sport'] },
    { icon: '⚾', tags: ['fun', 'baseball', 'sport'] },
    { icon: '🎾', tags: ['fun', 'tennis', 'sport', 'tenis'] },
    { icon: '🏐', tags: ['fun', 'volleyball', 'sport', 'voleibol'] },
    { icon: '🏉', tags: ['fun', 'rugby', 'sport'] },
    { icon: '🎱', tags: ['fun', 'billiards', 'pool', 'game', 'billar'] },
    { icon: '🎳', tags: ['fun', 'bowling', 'game', 'bolos'] },
    { icon: '⛳', tags: ['fun', 'golf', 'sport'] },
    { icon: '🎣', tags: ['fun', 'fishing', 'hobby', 'pesca'] },
    { icon: '🎨', tags: ['hobby', 'art', 'paint', 'draw', 'arte'] },
    { icon: '🎭', tags: ['hobby', 'theater', 'drama', 'mask', 'teatro'] },
    { icon: '📸', tags: ['hobby', 'camera', 'photo', 'picture', 'foto'] },
    { icon: '📷', tags: ['hobby', 'camera', 'photography', 'camara'] },
    { icon: '📹', tags: ['hobby', 'video', 'camera', 'record', 'grabacion'] },
    { icon: '🧶', tags: ['hobby', 'yarn', 'knitting', 'craft'] },
    { icon: '🧵', tags: ['hobby', 'thread', 'sewing', 'craft', 'costura'] },

    // Education & Work
    { icon: '📚', tags: ['education', 'book', 'school', 'study', 'libro'] },
    { icon: '📕', tags: ['education', 'book', 'reading', 'lectura'] },
    { icon: '📖', tags: ['education', 'open book', 'reading', 'lectura'] },
    { icon: '🎓', tags: ['education', 'graduation', 'degree', 'university', 'graduacion'] },
    { icon: '🏫', tags: ['education', 'school', 'building', 'college', 'escuela'] },
    { icon: '✏️', tags: ['work', 'pencil', 'write', 'draw', 'lapiz'] },
    { icon: '🖊️', tags: ['work', 'pen', 'write', 'ink', 'boligrafo'] },
    { icon: '📝', tags: ['work', 'memo', 'note', 'write', 'nota'] },
    { icon: '📋', tags: ['work', 'clipboard', 'list', 'task', 'lista'] },
    { icon: '📅', tags: ['work', 'calendar', 'date', 'schedule', 'calendario'] },
    { icon: '💼', tags: ['work', 'briefcase', 'business', 'job', 'maletin'] },
    { icon: '💻', tags: ['work', 'laptop', 'computer', 'tech', 'ordenador'] },
    { icon: '🖥️', tags: ['work', 'desktop', 'computer', 'monitor', 'pantalla'] },
    { icon: '🖨️', tags: ['work', 'printer', 'paper', 'office', 'impresora'] },
    { icon: '📎', tags: ['work', 'clip', 'office', 'attach'] },
    { icon: '📊', tags: ['work', 'chart', 'graph', 'stats', 'grafico'] },
    { icon: '📈', tags: ['work', 'chart', 'growth', 'up'] },
    { icon: '📉', tags: ['work', 'chart', 'loss', 'down'] },

    // Financial & Money
    { icon: '💰', tags: ['money', 'bag', 'rich', 'wealth', 'dinero'] },
    { icon: '💵', tags: ['money', 'dollar', 'cash', 'bill', 'billete'] },
    { icon: '💶', tags: ['money', 'euro', 'cash', 'bill', 'euro'] },
    { icon: '💷', tags: ['money', 'pound', 'cash', 'bill', 'libra'] },
    { icon: '💸', tags: ['money', 'wads', 'flying', 'spend', 'gasto'] },
    { icon: '💳', tags: ['money', 'credit', 'debit', 'card', 'tarjeta'] },
    { icon: '🧾', tags: ['money', 'receipt', 'bill', 'invoice', 'recibo'] },
    { icon: '🏦', tags: ['money', 'bank', 'building', 'deposit', 'banco'] },
    { icon: '🏧', tags: ['money', 'atm', 'withdraw', 'cash', 'cajero'] },
    { icon: '👛', tags: ['money', 'purse', 'wallet', 'women', 'monedero'] },
    { icon: '🪙', tags: ['money', 'coin', 'change', 'moneda'] },
    { icon: '💎', tags: ['money', 'gem', 'diamond', 'rich', 'joya'] },
    { icon: '⚖️', tags: ['money', 'scale', 'balance', 'law', 'balanza'] },

    // Family & People
    { icon: '👶', tags: ['family', 'baby', 'child', 'kid', 'bebe'] },
    { icon: '👦', tags: ['family', 'boy', 'child', 'kid', 'nino'] },
    { icon: '👧', tags: ['family', 'girl', 'child', 'kid', 'nina'] },
    { icon: '👨', tags: ['family', 'man', 'adult', 'hombre'] },
    { icon: '👩', tags: ['family', 'woman', 'adult', 'mujer'] },
    { icon: '👴', tags: ['family', 'old', 'man', 'grandpa', 'abuelo'] },
    { icon: '👵', tags: ['family', 'old', 'woman', 'grandma', 'abuela'] },
    { icon: '👪', tags: ['family', 'group', 'parents', 'familia'] },
    { icon: '🐶', tags: ['family', 'pet', 'dog', 'puppy', 'perro'] },
    { icon: '🐱', tags: ['family', 'pet', 'cat', 'kitten', 'gato'] },
    { icon: '🐹', tags: ['family', 'pet', 'hamster', 'mouse'] },
    { icon: '🐰', tags: ['family', 'pet', 'rabbit', 'bunny', 'conejo'] },
    { icon: '🦜', tags: ['family', 'pet', 'parrot', 'bird', 'loro'] },
    { icon: '🐠', tags: ['family', 'pet', 'fish', 'aquarium', 'pez'] },
    { icon: '🐾', tags: ['family', 'paw', 'animal', 'pet', 'huella'] },

    // Others & Symbols
    { icon: '🎁', tags: ['other', 'gift', 'present', 'birthday', 'regalo'] },
    { icon: '🎈', tags: ['other', 'balloon', 'party', 'celebrate', 'globo'] },
    { icon: '🎉', tags: ['other', 'party', 'popper', 'celebrate', 'fiesta'] },
    { icon: '🕯️', tags: ['other', 'candle', 'light', 'wax', 'vela'] },
    { icon: '💡', tags: ['other', 'bulb', 'idea', 'light', 'bombilla'] },
    { icon: '📦', tags: ['other', 'box', 'package', 'delivery', 'caja'] },
    { icon: '📧', tags: ['other', 'email', 'mail', 'letter', 'correo'] },
    { icon: '📫', tags: ['other', 'mailbox', 'post', 'letter', 'buzon'] },
    { icon: '🔒', tags: ['other', 'lock', 'security', 'safe', 'candado'] },
    { icon: '🔑', tags: ['other', 'key', 'access', 'door', 'llave'] },
    { icon: '❤️', tags: ['other', 'heart', 'love', 'like', 'corazon'] },
    { icon: '⭐', tags: ['other', 'star', 'favorite', 'rate', 'estrella'] },
    { icon: '⚠️', tags: ['other', 'warning', 'alert', 'danger', 'aviso'] },
    { icon: '⛔', tags: ['other', 'stop', 'restricted', 'no'] },
    { icon: '✅', tags: ['other', 'check', 'done', 'success', 'ok'] },
    { icon: '❌', tags: ['other', 'cross', 'wrong', 'fail', 'error'] },
    { icon: '❓', tags: ['other', 'question', 'help', 'ask', 'pregunta'] },
    { icon: '♻️', tags: ['other', 'recycle', 'environment', 'reciclaje'] },
    { icon: '🔋', tags: ['other', 'battery', 'power', 'energy', 'bateria'] }
];
